---
applications:
- name: sweater-sample
  host: sweater-sample-QA
  buildpack: liberty-for-java
  path: ../../target/${ARTIFACT_NAME}
  memory: 256M
  instances: 2
  timeout: 180
  env: 
    LOG_LEVEL: ERROR
  services:
  - slog_CSG-KPORG-RX-MS-SJ001_QA_sweater-sample
  - smon_nonprod_dynatrace
  - Auto-Scaling Dedicated-xn
